import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  membershipSection: {
    backgroundColor: 'transparent',
    paddingVertical: 50,
    paddingHorizontal: 30,
    borderRadius: 10,
    marginHorizontal: 20,
    marginVertical: 40,
    alignSelf: 'center',
    maxWidth: 1000,
    width: '100%',
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  columnLeft: {
    flex: 1,
    paddingLeft: 120,
    paddingRight: 90,
    marginLeft: -90,
    marginBottom: 0,
  },
  columnRight: {
    flex: 1,
    paddingLeft: 70,
    alignItems: 'flex-start',
    marginTop: 0,
  },
  divider: {
    width: 1,
    backgroundColor: '#2a2a2a',
    marginHorizontal: 10,
    height: '50%',
    alignSelf: 'center',
    marginVertical: 0,
  },
  membershipTitle: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 30,
    textAlign: 'left',
    lineHeight: 38,
  },
  offerText: {
    color: '#d4d9d0',
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 8,
    textAlign: 'left',
  },
  membershipPrice: {
    color: '#FFFFFF',
    fontSize: 20,
    marginBottom: 12,
    textAlign: 'left',
  },
  membershipDescription: {
    color: '#4a4e4f',
    fontSize: 18,
    lineHeight: 25,
    marginBottom: 20,
    textAlign: 'left',
  },
  membershipCta: {
    backgroundColor: '#f23a11',
    paddingVertical: 16,
    borderRadius: 3,
    alignItems: 'center',
    paddingHorizontal: 30,
    width: '100%',
    marginTop: 15,
  },
  ctaText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  scheduleTitle: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 20,
    marginTop: -5,
    textAlign: 'left',
  },
  scheduleItem: {
    color: '#4a4e4f',
    fontSize: 18,
    marginBottom: 8,
    textAlign: 'left',
  },
  scheduleGroup: {
    marginBottom: 20,
    alignItems: 'flex-start',
  },
  scheduleDay: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'left',
  },
  scheduleTime: {
    color: '#4a4e4f',
    fontSize: 18,
    marginTop: 6,
    textAlign: 'left',
  },
});

export default styles;
